# Generated by Django 2.2.9 on 2020-02-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataServer', '0002_auto_20200130_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('yno', models.IntegerField(primary_key=True, serialize=False)),
                ('usno', models.IntegerField()),
                ('regdate', models.DateField(blank=True, db_column='regDate', null=True)),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naverdatalab',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False)),
                ('searchkeyword', models.CharField(blank=True, db_column='searchKeyword', max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='endDate', null=True)),
                ('data', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'db_table': 'naverDataLab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('yno', models.IntegerField(db_column='userID', max_length=100)),
                ('kinds', models.IntegerField(blank=True, db_column='userEmail', max_length=100, null=True)),
                ('values', models.FloatField(db_column='userName', max_length=100)),
            ],
            options={
                'db_table': 'stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('tno', models.AutoField(primary_key=True, serialize=False)),
                ('recorddate', models.DateTimeField(blank=True, db_column='recordDate', null=True)),
                ('pointsubscriber', models.IntegerField(blank=True, db_column='pointSubscriber', null=True)),
                ('difsubscriber', models.IntegerField(blank=True, db_column='difSubscriber', null=True)),
                ('pointview', models.BigIntegerField(blank=True, db_column='pointView', null=True)),
                ('difview', models.IntegerField(blank=True, db_column='difView', null=True)),
            ],
            options={
                'db_table': 'trend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usno', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='userID', max_length=100)),
                ('useremail', models.CharField(blank=True, db_column='userEmail', max_length=100, null=True)),
                ('username', models.CharField(db_column='userName', max_length=100)),
                ('regdate', models.DateField(db_column='regDate')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CommunityYoutuberRelation',
        ),
        migrations.DeleteModel(
            name='Growth',
        ),
    ]
