# Generated by Django 2.2.9 on 2020-02-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataServer', '0003_auto_20200207_1148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='naverdatalab',
            table='naver_data_lab',
        ),
    ]
