# Generated by Django 2.2.9 on 2020-02-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataServer', '0004_auto_20200210_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('itno', models.IntegerField(primary_key=True, serialize=False)),
                ('itname', models.CharField(db_column='itName', max_length=50)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestUserRelation',
            fields=[
                ('usno', models.ForeignKey(db_column='usno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataServer.User')),
            ],
            options={
                'db_table': 'interest_user_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempMonth',
            fields=[
                ('month_date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'temp_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempWeek',
            fields=[
                ('week_lastday', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'temp_week',
                'managed': False,
            },
        ),
    ]
