export default {
  GET_TEST: "getTest",
  GET_YOUTUBERS_PER_CATEGORY: "getyoutuberspercategory",
  CHANGE_CATEGORY_LOADING: "changecategoryloading",
  CHANGE_CURRENT_CATEGORY: "chagecurrentcateagory",
  GET_YOUTUBER: "getyoutuber",
  SEARCH_YOUTUBER: "searchyoutuber",
  ADD_COMPARED_YOUTUBER: "addcomparedyoutuber",
  GET_COMPARE_YOUTUBER: "getcompareyoutuber",
  INSERT_YOUTUBUER: "insertyoutbuer",
  GET_MANYTOP5: "getmanytop5",
  GET_ALLYOUTUBER: "getallyoutuber",
  GET_YNO_FROM_URL: "getynofromurl",
  GET_STATUS_FROM_YNO: "getstatusfromyno",
};
